# Generated by Django 6.0.6 on 2026-07-18 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField(verbose_name='Tezlik (WPM)')),
                ('accuracy', models.IntegerField(verbose_name='Anriqlik (%)')),
                ('date_earned', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'ordering': ['-wpm', '-accuracy'],
            },
        ),
    ]
